# Site settings
title:          Obfuscated Memories
description:    "Personal blog of Irshad P I"
url:            "https://irshadpi.me"

# Google Analytics
google_analytics: UA-158042880-1

# Author
author:
  name:         Irshad
  url:          https://irshadpi.me

# Build settings
markdown:       kramdown
include:
  - _pages

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

header_pages:
  - _pages/about.md
  - _pages/contact.md

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap
  # - jemoji #Uncomment this to allow emoji in your post

# Permalinks
permalink:      /:title
paginate:       6

# Excludes
exclude: [ Gemfile, Gemfile.lock, tale.gemspec ]
