# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Obfuscated Memories
email: irshadpi77@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Just a random description goes here.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://irshadshalu.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: irshadshalu
github_username:  irshadshalu

# Build settings
markdown: kramdown
# remote_theme: b2a3e8/jekyll-theme-console
remote_theme: thelehhman/plainwhite-jekyll
style: dark
header_pages:
  - index.md
  - contact.md

footer: Crafted with Jekyll, Served using Github Pages 
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
plainwhite:
  name: Irshad P I
  tagline: Developer.
  date_format: "%b %-d, %Y"

  social_links:
    twitter: irshadshalu
    github: irshadshalu
    linkedIn: in/irshadshalu # format: locale/username
  analytics_id:
    'UA-158042880-1'
show_excerpts: true

